# Site settings
title: Lagishetty Vasavi
description: A simple blog about me
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Vasavi Lagishetty
user_description: Hello! I'm Lagishetty Vasavi, Currently I'm pursuing my final year of Bachelor of Technology, Computer Science from Vardhaman College of Engineering. I'm working as Software Trainee Engineer at ValueLabs (www.valuelabs.com), Hyderabad. Working on various technologies like Low Code Platforms, ReactJS, and also on Swift-Xcode(IoS). I felt Enthusiastic in open-source contributions, problem-solving, algorithms, love to explore and build real-time applications.
user_title: Software Trainee Engineer at ValueLabs, Hyderabad
email: vasavi2910@gmail.com
github_username:  VasaviLagishetty
hackerrank_username: vasavi_2910
linkedin_username:  vasavi2910

Education:
  - course: Bachelor's Degree, Computer science
    college: Vardhaman college of Engg
    percentage: 9.33*
    completion: June 2020
  - course: Intermediate, M.P.C
    college: Srichaitanya Junior College
    percentage: 95.4% 
    completion: March 2016
  - course: School, S.S.C
    college: Srichaitanya
    percentage: 9.5
    completion: March 2014

Projects:
  - img: /assets/img/classify_binder.jpg
    source_url: https://github.com/VasaviLagishetty/Classify-Binder/
    title: The Classify Binder
    subtitle: File Classification
    description: An application which deals with local file system directories and folders and classifies them into respective folders which makes user task of accessing files easy in that particular directory.
  - img: /assets/img/movie_search.png
    source_url: https://github.com/VasaviLagishetty/MovieSearch
    title: Movie Search
    subtitle: Keyword based search
    description: Developing a React JS application that fetches the data from OMDB API and displays on a web page according to the user search keyword and category.
  - img: /assets/img/covid19.png
    source_url: https://github.com/VasaviLagishetty/COVID19
    title: COVID19 Analysis
    subtitle: Visualizations
    description: A graph plot that describes overall covid19 cases, geographical Visualizations and also top 10 countries with respective confirmed, deaths, recovered cases.
  - img: /assets/img/hcr.png
    source_url: https://code.swecha.org/team2/charrecognition
    title: HCR
    subtitle: Handwritten character recognition
    description: Built a Machine Learning model, Web Application in python to recognize the handwritten digits from images. For future enhancement we will focus on alphabets, numeric data and telugu characters.
  - img: /assets/img/pwa.png
    source_url: https://github.com/VasaviLagishetty/Progressive-Web-App
    title: PWA
    subtitle: Progressive Web Apps
    description: A technical paper presentation on Progressive Web Apps. PWAs are web applications that are regular web pages or websites, but can appear to the user like traditional applications or native mobile applications.
  
social_links:
  - label: My Github
    faicon: github
    link: https://github.com/VasaviLagishetty
  - label: My HackerRank
    faicon: hackerrank
    link: https://www.hackerrank.com/vasavi_2910
  - label: My Linkedin
    faicon: linkedin
    link: https://www.linkedin.com/in/vasavi2910
  - label: My Sourcer
    faicon: chart-line
    link: https://sourcerer.io/vasavilagishetty
  - label: My facebook
    faicon: facebook
    link: https://www.facebook.com/vasavi2910
    
Nav_bar:
  - section: About
    url: /about
  - section: Projects
    url: /projects
  - section: Resume
    url: /about
  - section: Contact
    url: /contact


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
